# Generated by Django 4.0.1 on 2023-10-18 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='btc_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='btc_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='executed_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='temp_id', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='average_weighted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='btc_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ips',
            field=models.Field(default=[]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profit_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='subprofiles',
            field=models.Field(default={}),
        ),
        migrations.AddField(
            model_name='profile',
            name='usd_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
